MySchool3/Models/Entities/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//namespace MySchool3.Models.Entities
namespace MySchool3.Models
{
    public class Course
    {
        public int CourseID { get; set; }
        public string Name { get; set; }
        public string CourseCode { get; set; }
    }
}

MySchool3/Models/Entities/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySchool3.Models
{
    public class Customer
    {
        public string ClientName { get; set; }
        public string ClientAdress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientInfo { get; set; }
    }
}

MySchool3/Components/CourseListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MySchool3.Models;
using Microsoft.AspNetCore.Mvc;

namespace MySchool3.Components
{
    public class CourseListViewComponent : ViewComponent
    {
        private ISchoolRepository repository;

        public CourseListViewComponent(ISchoolRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View("CourseList", repository.Courses);
        }
    }
}

MySchool3/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySchool3.Controllers
{
    public class ExamController : Controller
    {
        public ViewResult ExamOne()
        {
            ViewBag.title = "Exam One - My school";
            return View();
        }
        public ViewResult ExamTwo()
        {
            ViewBag.title = "Exam Two - My School";
            return View();
        }
        public ViewResult ExamThree()
        {
            ViewBag.title = "Exam Three - My School";
            return View();
        }
    }
}

MySchool3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using MySchool3.Models;
using MySchool3.Infrastructure;

namespace MySchool3.Controllers
{
    public class HomeController : Controller

    {
        private ISchoolRepository repository;

        //constructor
        //in the controller, only use the interface to the repository
        public HomeController(ISchoolRepository repo)
        {
            repository = repo;
        }

        // called in _Mainlayout navigation
        public ViewResult Index()
        {
            //change title of web browser tab
            ViewBag.title = "Home - My School";
            return View();
        }

        [HttpPost]
        public ViewResult Index(Student student)
        {
            ViewBag.Name = $"Välkommen {student.Name}";
            return View("NewStudent");
        }

        public ViewResult Roster()
        {
            //change title of web browser tab
            ViewBag.title = "Roster - My School";

            //try to aim for only passing limited amount of information
            //this adds/enables data to the view
            return View(repository);
        }

        public ViewResult Courses()
        {
            //change title of web browser tab
            ViewBag.title = "Courses - My School";
            return View(repository.Courses);
        }

        public ViewResult Cookies()
        {
            //change title of web browser tab
            ViewBag.title = "Cookies - My School";
            return View();
        }

        public ViewResult WriteCookies(string setting, string settingValue, bool isPersistent)
        {

            if (isPersistent)
            {
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Append(setting, WebUtility.UrlEncode(settingValue), options);
            }
            else
            {
                Response.Cookies.Append(setting, WebUtility.UrlEncode(settingValue));
            }
            ViewBag.Message = "Cookie written succesfully!";
            return View("Cookies");
        }

        public ViewResult ReadCookie()
        {
            ViewBag.FontName = WebUtility.UrlDecode(Request.Cookies["fontName"]);
            ViewBag.FontSize = WebUtility.UrlDecode(Request.Cookies["fontSize"]);
            ViewBag.FontColor = WebUtility.UrlDecode(Request.Cookies["fontColor"]);

            if (string.IsNullOrEmpty(ViewBag.FontName))
            {
                ViewBag.FontName = "Arial";
            }
            if (string.IsNullOrEmpty(ViewBag.FontSize))
            {
                ViewBag.FontSize = "22px";
            }
            if (string.IsNullOrEmpty(ViewBag.FontColor))
            {
                ViewBag.FontColor = "Blue";
            }

            return View();

        }

        public ViewResult Exam()
        {
            //change title of web browser tab
            ViewBag.title = "Exam - My School";
            return View();
        }

        public ViewResult ShowTeacherInfo(int id)
        {
            ViewBag.ID = id;
            return View();
        }

        public ViewResult ShowStudentInfo(int id)
        {
            var studentDetail = repository.GetStudentDetail(id);
            return View(studentDetail);
        }

        public ViewResult NewStudent(string fullname)
        {
            ViewBag.Name = fullname;
            return View();
        }

        public ViewResult Customers()
        {
            ViewBag.Name = "Customers - My School??";

            var myCustomer = HttpContext.Session.GetJson<Customer>("NewCustomer");
            if (myCustomer == null)
            {
                return View();
            }
            else
            {
                return View(myCustomer);
            }
        }

        [HttpPost]
        public ViewResult ValidateCustomer(Customer cust)
        {
            HttpContext.Session.SetJson("NewCustomer", cust);
            return View(cust);
        }

        public ViewResult SavedCustomer()
        {
            //here lies the call to persistent storage

            //always destroy session after call to persistent
            HttpContext.Session.Remove("NewCustomer");
            return View();
        }
    }
}

MySchool3/Views/Home/Cookies.cshtml
<h1>Welcome to the CookieMonster</h1>
<h2>Specify your preferences:</h2>

<form asp-controller="Home" asp-action="WriteCookies">
    <select name="setting">
        <option value="fontName">Font name</option>
        <option value="fontSize">Font size</option>
        <option value="fontColor">Color</option>
    </select>
    <input type="text" name="settingValue" />
    <input type="checkbox" name="isPersistent"
           value="true" /> Is Persistent?
    <input type="submit" value="Write Cookie" />
</form>

<h4>@ViewBag.Message</h4>

<h4>
    <a asp-action="ReadCookie" asp-controller="Home">
        Read Cookies
    </a>
</h4>

MySchool3/Views/Home/Courses.cshtml
@*IEnumerable is used for internal sources, used in views (no sql call)*@

@model IEnumerable<Course>

<h1>These are my courses</h1>
<!--drop down list-->
<select>
    <option> Choose course: </option>
    @foreach (Course course in Model)
    {
        <option>@course.Name</option>
    }
</select>

MySchool3/Views/Home/Customers.cshtml
@model Customer
<form asp-controller="Home" asp-action="ValidateCustomer" method="post">
    <p>
        <label asp-for="ClientName">Your name:</label>
        <input asp-for="ClientName" />
    </p>
    <p>
        <label asp-for="ClientAdress">Your adress:</label>
        <input asp-for="ClientAdress" />
    </p>

    <p>
        <label asp-for="ClientPhone">Your phone:</label>
        <input asp-for="ClientPhone" />
    </p>
    <p>
        <label asp-for="ClientInfo">Extra info:</label>
        <input asp-for="ClientInfo" />
    </p>

    <p>
        <button type="Submit">Save customer</button>
    </p>
</form>

MySchool3/Views/Home/Exam.cshtml
<h1>
    Exams   
</h1>

<h2>Choose what task you would like submit</h2>

<ul>
    <li><a asp-controller="Exam" asp-action="ExamOne">Exam 1</a></li>
    <li><a asp-controller="Exam" asp-action="ExamTwo">Exam 2</a></li>
    <li><a asp-controller="Exam" asp-action="ExamThree">Exam 3</a></li>
</ul>

MySchool3/Views/Home/Index - Copy.cshtml
@model Student

<h1>Welcome to my School!!!!!</h1>

<form asp-controller="Home" asp-action="Index" method="post">
    <div asp-validation-summary="All"></div>
    <p>
        <!-- asp-for connects the model (Student) variable directly-->
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </p>
    <p>
        <input type="submit" value="Submit" />
        <input type="reset" />
    </p>
</form>

MySchool3/Views/Home/Index.cshtml
@model Student

<h1>Welcome to my School!!!!!</h1>

<form asp-controller="Home" asp-action="Index" method="post">
    <div asp-validation-summary="All"></div>
    <p>
        <!-- asp-for connects the model (Student) variable directly-->
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </p>
    <p>
        <input type="submit" value="Submit" />
        <input type="reset" />
    </p>
</form>

MySchool3/Views/Home/NewStudent.cshtml
@{

}
<h1>@ViewBag.Name</h1>

MySchool3/Views/Home/ReadCookie.cshtml
<h1>Current state of the cookies: </h1>


<!--cookies good for temp data-->
<!--cookies good for less/small data-->
<!--cookies saved in client/browser-->
<!--cookies dont have much security-->
<!--cookies accessed thru response and requests-->


<p style="font-family:@ViewBag.FontName">Font name: @ViewBag.FontName</p>
<p style="font-size:@ViewBag.FontSize">Font size: @ViewBag.FontSize</p>
<p style="color:@ViewBag.FontColor">Font color: @ViewBag.FontColor</p>

<a asp-controller"Home" asp-action="Index">Go back to home page</a>

MySchool3/Views/Home/Roster.cshtml
@model ISchoolRepository

<h1>Teachers and students</h1>

<h2>These are the students</h2>

@foreach (Student student in Model.Students)
{
    <p>
        <a asp-controller"Home" asp-action="ShowStudentInfo" asp-route-id="@student.StudentID">@student.Name</a>
    </p>

}

<h2>These are the teachers</h2>


@foreach (Teacher teacher in Model.Teachers)
{

    <p>
        <a asp-controller"Home" asp-action="ShowTeacherInfo" asp-route-id="@teacher.TeacherID">@teacher.Name</a>
    </p>
}

MySchool3/Views/Home/SavedCustomer.cshtml
<h1>thank you!!</h1>
<p>
    <a asp-controller="Home" asp-action="Index">Go back to home</a>
</p> 

MySchool3/Views/Home/Sessions.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MySchool3/Views/Home/ShowStudentInfo.cshtml
@model Student

<h1>Student details</h1>

<h2>Ýou were looking for:</h2>

<p>@Model.Name</p>
<p>@Model.StudentID</p>
<p>@Model.Code</p>

MySchool3/Views/Home/ShowTeacherInfo.cshtml
<h1>Teacher details</h1>

<h2>You searched for:</h2>

@await Component.InvokeAsync("ShowOneTeacher", ViewBag.ID)

@await Component.InvokeAsync("CourseList") 

MySchool3/Views/Home/ValidateCustomer.cshtml
@model Customer

<p>@Model.ClientName</p>
<p>@Model.ClientAdress</p>
<p>@Model.ClientPhone</p>
<p>@Model.ClientInfo</p>

<p>
    <a asp-controller="Home" asp-action="Customers">Go back and change</a>
    <a asp-controller="Home" asp-action="SavedCustomer">Save Customer</a>
</p> 